- hosts: all
  become: true
  tasks:
    - name: Install packages
      apt:
        name: "{{ item }}"
        update_cache: yes
        cache_valid_time: 3600
      with_items:
        - nodejs
        - nodejs-legacy
        - npm
        - redis-server
